### ISSUE TITLE
Maybe a bug, but probably not.

### ISSUE THREAD

**Issue by everythingability** [WolfVector/neptune-component#1]
Hi,

nice library, thanks. I've been trying to implement it in the Apps Script environment (which may be what is really causing the issue in actuality ).

I made a url endpoint that returns a json result {"rows":[{"Initials":"KW","Notes":"Dave checking user re... etc

It has an id and in this case the title is defined in the n-table like this  n-title="Item Title"          

So the error I am getting is ...

<img width="715" alt="image" src="https://github.com/WolfVector/neptune-component/assets/96276/8768e917-348e-4b87-b148-da6769f7277b">
<img width="403" alt="image" src="https://github.com/WolfVector/neptune-component/assets/96276/03cdd581-1ddc-4444-a833-f5ac176850b2">

Is it maybe because I'm trying to load 120 records (and it's taking too long?)

Is it perhaps that because Apps Script web apps monkey with the HTML that n-table can't find the right bit of the HTML?

I have had no problems with other similar tools like jQueryTable but can get n-table running.

Any ideas?

Thank you.

**Comment by WolfVector** [comment]
Hi. It seems like JS is executing before the whole HTML loaded. Maybe you are putting the `<script>` tag inside `<head>`?

For example, if you execute the next HTML file it will give you the same error:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <script>
        const element = document.createElement("dialog")
        element.innerHTML = "A test"

        document.body.append(element) // Uncaught TypeError: Cannot read properties of null (reading 'append')
    </script>

</head>
<body>
    hola
</body>
</html>
```

So try putting the `<script>` tag at the end of `<body>`

```html
<!doctype html>
<html lang="en">
  <head>
    <title>Example</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/WolfVector/neptune-component/src/neptune.min.css" />

  </head>
  <body>
    
    <script src="https://cdn.jsdelivr.net/gh/WolfVector/neptune-component/src/neptune.min.js"></script>
  </body>
</html> 
```

Let me know if this fixes it.

**Comment by everythingability** [comment]
Ah - yes. Thank you ! That got it ALMOST working but then it hits into Apps Script monkeying re CORS...

<img width="944" alt="image" src="https://github.com/WolfVector/neptune-component/assets/96276/62945f4f-638e-45dc-b908-48035f14001e">

The URL I use to load the data is the same as the webapp, but Apps Script is a rule unto itself...

Thank you anyway.

**Comment by everythingability** [comment]
I mean the same with a query tag ?get=data returns JSON properly formatted...

**Comment by WolfVector** [comment]
Yeah, the CORS is something related to the server, in this case Apps Script. But thanks for raising the issue, I'm going to add the `load` event to the library so that the `<script>` tag can be place anywhere in the HTML.

**Comment by everythingability** [comment]
Thanks for your help...

**Comment by everythingability** [comment]
I managed to solve this. It's an Apps Script related issue at heart. The web app was made to be available to anyone at my organisation, and so when your code tried to load the json, of course, it failed. If I make it available to "Anyone", i.e public, the json loads fine, and it all looks good.

**Comment by WolfVector** [comment]
Good to hear you fixed it!

**Comment by everythingability** [comment]
Almost fixed...

Sorry to bang on, but if I could, instead of adding a URL endpoint for the various features... add  function names (assuming that they were passed an id argument) then I could make this work with full Google security so the JSON endpoint didn't have to publicly available. Whilst leaving the data endpoint obfuscated by being at the end of a horrible AppsScript web app URL would be "kind of" OK, given I can auth the main page.... it'd be better for me if it worked like this.

The function, in my index.html,  might be something like (excuse the AppsScript-y stuff which may only make partial sense)...

```
<html>
<script>
function getData(id){
    google.script.run.doGetData()
}

function updateDone(msg){
  console.log("updated: " + msg)
}

function update(id){
    google.script.run.withSuccessHandler(updateDone).doUpdate(id)
}
</script>
<body>

<div 
    n-table                                              <!-- Define the table -->
    n-url="doGetData"                          <!-- local function to get the data -->
    n-theme="normal" 
    n-update="update"   

etc
```

**Comment by WolfVector** [comment]
Hi. This seems possible, I could add a regex to detect if the parameter is a path or a function name. I almost have ready the next version, I'm going to include this change to it.

**Comment by WolfVector** [comment]
Hi. This seems possible, I could add a regex to detect if the parameter is a path or a function name. However, your function will have to return the data in order for the table to display:

```js
function getData(id){
    let data = google.script.run.doGetData()
    return data
}

function updateDone(msg){
  console.log("updated: " + msg)
}

function update(id){
    google.script.run.withSuccessHandler(updateDone).doUpdate(id)
}
```

I don't know if AppsScript allows that

**Comment by everythingability** [comment]
Oh yeah... that's fine. AppsScript "is" Javascript with just a few odd
caveats and ways of working.

**Comment by WolfVector** [comment]
Ok, I'm going to test this and see if it is viable to implement. If it is, then it will be included in the next version, which will probably be published on sunday
